apiVersion: v1
kind: Service
metadata:
  name: wordpuzzle-service
spec:
  selector:
    app: wordpuzzle
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31125
  type: NodePort
